services:
  app:
    build: 
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ~/.ssh:/opt/Heisenberg/.ssh
      - ..:/opt/Heisenberg/code
    command: ["tail -f /dev/null"]

  redis:
    image: "redis:alpine"
    command: redis-server --requirepass sOmE_sEcUrE_pAsS
    # ports:
    #  - "6379:6379"
